apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jeuyrko6e-python 
  janus-idp.io/tekton: jeuyrko6e-python
  backstage.io/kubernetes-id: jeuyrko6e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jeuyrko6e-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  